version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      # We only group minor and patch updates so that its easy to review and
      # accept without too much fuss. For major updates we still want a separate
      # PR for each dependency so we can discuss and review it properly.
      patches:
        update-types:
          - patch
      minor:
        update-types:
          - minor

  - package-ecosystem: npm
    directory: /packages/remeda
    schedule:
      interval: monthly
    groups:
      # We only group minor and patch updates so that its easy to review and
      # accept without too much fuss. For major updates we still want a separate
      # PR for each dependency so we can discuss and review it properly.
      patches:
        update-types:
          - patch
      minor:
        update-types:
          - minor

  - package-ecosystem: npm
    directory: /packages/docs
    schedule:
      interval: monthly
    groups:
      # We only group minor and patch updates so that its easy to review and
      # accept without too much fuss. For major updates we still want a separate
      # PR for each dependency so we can discuss and review it properly.
      patches:
        update-types:
          - patch
      minor:
        update-types:
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
