name: ðŸ¦• Publish to JSR.io

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      tag_name:
        description: "The tag name to sync to JSR.io (e.g., v2.34.56)"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      # @see https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
      id-token: write
      contents: read

    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4
        with:
          # Checkout the specific tag
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}

      - name: âŽ” Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: ðŸ“¥ Download Dependencies
        uses: bahmutov/npm-install@v1
        env:
          HUSKY: 0

      - name: ðŸ“ Update Version
        working-directory: packages/remeda
        run: |
          VERSION="${{ github.event.release.tag_name || github.event.inputs.tag_name }}"
          jq --arg version "${VERSION#v}" '.version = $version' jsr.json > jsr.json.tmp
          mv jsr.json.tmp jsr.json

      - name: ðŸš€ Publish
        # We allow dirty here because our jsr.json file has been modified and we
        # don't want to commit it back to the repo.
        run: npm run --workspace=remeda publish:jsr -- --allow-dirty
